apiVersion: v1
kind: Service
metadata:
  name: view-db-mongo
  namespace: s6-namespace
spec:
  selector:
    app: view-db-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-db-mongo
  namespace: s6-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-db-mongo
  template:
    metadata:
      labels:
        app: view-db-mongo
    spec:
      containers:
        - name: view-db-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
