name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: marcinfonty
  DOCKERHUB_PASSWORD: Iow0RTtwmu

jobs:
  build_cms:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push CMS
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Content_Managment_Service/Dockerfile
        push: true
        tags: <DOCKERHUB_USERNAME>/cms:latest
    - name: Send metrics to DataDog
      run: |
        STATUS=$?
        if [ $STATUS -eq 0 ]; then
          BUILD_STATUS=1
        else
          BUILD_STATUS=0
        fi
        curl -X POST -H "Content-type: application/json" \
        -d '{
          "series": [
            {
              "metric": "cms.build.success",
              "points": [[$(date +%s), $BUILD_STATUS]],
              "type": "gauge",
              "host": "github",
              "tags": ["github:actions"]
            }
          ]
        }' \
        "https://api.datadoghq.com/api/v1/series?api_key=${{ secrets.DATADOG_API_KEY }}"

  build_ehs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push EHS
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Event_Handler_Service/Dockerfile
        push: true
        tags: <DOCKERHUB_USERNAME>/ehs:latest
    - name: Send metrics to DataDog
      run: |
        STATUS=$?
        if [ $STATUS -eq 0 ]; then
          BUILD_STATUS=1
        else
          BUILD_STATUS=0
        fi
        curl -X POST -H "Content-type: application/json" \
        -d '{
          "series": [
            {
              "metric": "ehs.build.success",
              "points": [[$(date +%s), $BUILD_STATUS]],
              "type": "gauge",
              "host": "github",
              "tags": ["github:actions"]
            }
          ]
        }' \
        "https://api.datadoghq.com/api/v1/series?api_key=${{ secrets.DATADOG_API_KEY }}"

  build_fs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push FS
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Feed_Service/Dockerfile
        push: true
        tags: <DOCKERHUB_USERNAME>/fs:latest
    - name: Send metrics to DataDog
      run: |
        STATUS=$?
        if [ $STATUS -eq 0 ]; then
          BUILD_STATUS=1
        else
          BUILD_STATUS=0
        fi
        curl -X POST -H "Content-type: application/json" \
        -d '{
          "series": [
            {
              "metric": "fs.build.success",
              "points": [[$(date +%s), $BUILD_STATUS]],
              "type": "gauge",
              "host": "github",
              "tags": ["github:actions"]
            }
          ]
        }' \
        "https://api.datadoghq.com/api/v1/series?api_key=${{ secrets.DATADOG_API_KEY }}"
